// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TravelRestrictionSnapshotsColumns holds the columns for the "travel_restriction_snapshots" table.
	TravelRestrictionSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeInt64},
		{Name: "data", Type: field.TypeJSON},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "travel_restriction_snapshot_previous", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// TravelRestrictionSnapshotsTable holds the schema information for the "travel_restriction_snapshots" table.
	TravelRestrictionSnapshotsTable = &schema.Table{
		Name:       "travel_restriction_snapshots",
		Columns:    TravelRestrictionSnapshotsColumns,
		PrimaryKey: []*schema.Column{TravelRestrictionSnapshotsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "travel_restriction_snapshots_travel_restriction_snapshots_previous",
				Columns: []*schema.Column{TravelRestrictionSnapshotsColumns[4]},

				RefColumns: []*schema.Column{TravelRestrictionSnapshotsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TravelRestrictionSnapshotsTable,
	}
)

func init() {
	TravelRestrictionSnapshotsTable.ForeignKeys[0].RefTable = TravelRestrictionSnapshotsTable
}
