// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/ivanvanderbyl/entbug/ent/migrate"

	"github.com/ivanvanderbyl/entbug/ent/travelrestrictionsnapshot"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// TravelRestrictionSnapshot is the client for interacting with the TravelRestrictionSnapshot builders.
	TravelRestrictionSnapshot *TravelRestrictionSnapshotClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.TravelRestrictionSnapshot = NewTravelRestrictionSnapshotClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                       ctx,
		config:                    cfg,
		TravelRestrictionSnapshot: NewTravelRestrictionSnapshotClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:                    cfg,
		TravelRestrictionSnapshot: NewTravelRestrictionSnapshotClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		TravelRestrictionSnapshot.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.TravelRestrictionSnapshot.Use(hooks...)
}

// TravelRestrictionSnapshotClient is a client for the TravelRestrictionSnapshot schema.
type TravelRestrictionSnapshotClient struct {
	config
}

// NewTravelRestrictionSnapshotClient returns a client for the TravelRestrictionSnapshot from the given config.
func NewTravelRestrictionSnapshotClient(c config) *TravelRestrictionSnapshotClient {
	return &TravelRestrictionSnapshotClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `travelrestrictionsnapshot.Hooks(f(g(h())))`.
func (c *TravelRestrictionSnapshotClient) Use(hooks ...Hook) {
	c.hooks.TravelRestrictionSnapshot = append(c.hooks.TravelRestrictionSnapshot, hooks...)
}

// Create returns a create builder for TravelRestrictionSnapshot.
func (c *TravelRestrictionSnapshotClient) Create() *TravelRestrictionSnapshotCreate {
	mutation := newTravelRestrictionSnapshotMutation(c.config, OpCreate)
	return &TravelRestrictionSnapshotCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TravelRestrictionSnapshot entities.
func (c *TravelRestrictionSnapshotClient) CreateBulk(builders ...*TravelRestrictionSnapshotCreate) *TravelRestrictionSnapshotCreateBulk {
	return &TravelRestrictionSnapshotCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TravelRestrictionSnapshot.
func (c *TravelRestrictionSnapshotClient) Update() *TravelRestrictionSnapshotUpdate {
	mutation := newTravelRestrictionSnapshotMutation(c.config, OpUpdate)
	return &TravelRestrictionSnapshotUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TravelRestrictionSnapshotClient) UpdateOne(trs *TravelRestrictionSnapshot) *TravelRestrictionSnapshotUpdateOne {
	mutation := newTravelRestrictionSnapshotMutation(c.config, OpUpdateOne, withTravelRestrictionSnapshot(trs))
	return &TravelRestrictionSnapshotUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TravelRestrictionSnapshotClient) UpdateOneID(id int) *TravelRestrictionSnapshotUpdateOne {
	mutation := newTravelRestrictionSnapshotMutation(c.config, OpUpdateOne, withTravelRestrictionSnapshotID(id))
	return &TravelRestrictionSnapshotUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TravelRestrictionSnapshot.
func (c *TravelRestrictionSnapshotClient) Delete() *TravelRestrictionSnapshotDelete {
	mutation := newTravelRestrictionSnapshotMutation(c.config, OpDelete)
	return &TravelRestrictionSnapshotDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *TravelRestrictionSnapshotClient) DeleteOne(trs *TravelRestrictionSnapshot) *TravelRestrictionSnapshotDeleteOne {
	return c.DeleteOneID(trs.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *TravelRestrictionSnapshotClient) DeleteOneID(id int) *TravelRestrictionSnapshotDeleteOne {
	builder := c.Delete().Where(travelrestrictionsnapshot.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TravelRestrictionSnapshotDeleteOne{builder}
}

// Query returns a query builder for TravelRestrictionSnapshot.
func (c *TravelRestrictionSnapshotClient) Query() *TravelRestrictionSnapshotQuery {
	return &TravelRestrictionSnapshotQuery{config: c.config}
}

// Get returns a TravelRestrictionSnapshot entity by its id.
func (c *TravelRestrictionSnapshotClient) Get(ctx context.Context, id int) (*TravelRestrictionSnapshot, error) {
	return c.Query().Where(travelrestrictionsnapshot.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TravelRestrictionSnapshotClient) GetX(ctx context.Context, id int) *TravelRestrictionSnapshot {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNext queries the next edge of a TravelRestrictionSnapshot.
func (c *TravelRestrictionSnapshotClient) QueryNext(trs *TravelRestrictionSnapshot) *TravelRestrictionSnapshotQuery {
	query := &TravelRestrictionSnapshotQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := trs.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(travelrestrictionsnapshot.Table, travelrestrictionsnapshot.FieldID, id),
			sqlgraph.To(travelrestrictionsnapshot.Table, travelrestrictionsnapshot.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, travelrestrictionsnapshot.NextTable, travelrestrictionsnapshot.NextColumn),
		)
		fromV = sqlgraph.Neighbors(trs.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPrevious queries the previous edge of a TravelRestrictionSnapshot.
func (c *TravelRestrictionSnapshotClient) QueryPrevious(trs *TravelRestrictionSnapshot) *TravelRestrictionSnapshotQuery {
	query := &TravelRestrictionSnapshotQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := trs.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(travelrestrictionsnapshot.Table, travelrestrictionsnapshot.FieldID, id),
			sqlgraph.To(travelrestrictionsnapshot.Table, travelrestrictionsnapshot.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, travelrestrictionsnapshot.PreviousTable, travelrestrictionsnapshot.PreviousColumn),
		)
		fromV = sqlgraph.Neighbors(trs.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TravelRestrictionSnapshotClient) Hooks() []Hook {
	return c.hooks.TravelRestrictionSnapshot
}
