// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ivanvanderbyl/entbug/ent/predicate"
	"github.com/ivanvanderbyl/entbug/ent/travelrestrictionsnapshot"
)

// TravelRestrictionSnapshotDelete is the builder for deleting a TravelRestrictionSnapshot entity.
type TravelRestrictionSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *TravelRestrictionSnapshotMutation
}

// Where adds a new predicate to the TravelRestrictionSnapshotDelete builder.
func (trsd *TravelRestrictionSnapshotDelete) Where(ps ...predicate.TravelRestrictionSnapshot) *TravelRestrictionSnapshotDelete {
	trsd.mutation.predicates = append(trsd.mutation.predicates, ps...)
	return trsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (trsd *TravelRestrictionSnapshotDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(trsd.hooks) == 0 {
		affected, err = trsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TravelRestrictionSnapshotMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			trsd.mutation = mutation
			affected, err = trsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(trsd.hooks) - 1; i >= 0; i-- {
			mut = trsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, trsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (trsd *TravelRestrictionSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := trsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (trsd *TravelRestrictionSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: travelrestrictionsnapshot.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: travelrestrictionsnapshot.FieldID,
			},
		},
	}
	if ps := trsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, trsd.driver, _spec)
}

// TravelRestrictionSnapshotDeleteOne is the builder for deleting a single TravelRestrictionSnapshot entity.
type TravelRestrictionSnapshotDeleteOne struct {
	trsd *TravelRestrictionSnapshotDelete
}

// Exec executes the deletion query.
func (trsdo *TravelRestrictionSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := trsdo.trsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{travelrestrictionsnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (trsdo *TravelRestrictionSnapshotDeleteOne) ExecX(ctx context.Context) {
	trsdo.trsd.ExecX(ctx)
}
