// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TravelRestrictionSnapshot is the predicate function for travelrestrictionsnapshot builders.
type TravelRestrictionSnapshot func(*sql.Selector)
